print("========================================")
print("        ACHILLES' SHIELD")
print("             ASPIS")
print("    AI Security & Safety Agent")
print("========================================")
print()
print("Version: 0.1")
print()
print("Observe. Analyze. Protect.")
print("Never act beyond authority.")
print()
print("ASPIS ready.")